version: "3"
services:
  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5422:5432

  redis:
    image: redis
    volumes:
      - redis-data:/var/lib/redis/data

  web:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3001:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    volumes:
      - es-data:/var/lib/elasticsearch/data
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq
  #   volumes:
  #     - .:/myapp
  #   depends_on:
  #     - redis

volumes:
  pg-data:
  redis-data:
  es-data:
